#############################################################################
# Makefile for building: ResizableSplitScreen
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  ../../ResizableSplitScreen.pro
# Template: app
# Command: /home/vision/Qt/5.15.2/gcc_64/bin/qmake -o Makefile ../../ResizableSplitScreen.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../../../ResizableSplitScreen -I. -I/home/vision/Qt/5.15.2/gcc_64/include -I/home/vision/Qt/5.15.2/gcc_64/include/QtQuickControls2 -I/home/vision/Qt/5.15.2/gcc_64/include/QtQuick -I/home/vision/Qt/5.15.2/gcc_64/include/QtMultimedia -I/home/vision/Qt/5.15.2/gcc_64/include/QtGui -I/home/vision/Qt/5.15.2/gcc_64/include/QtQmlModels -I/home/vision/Qt/5.15.2/gcc_64/include/QtQml -I/home/vision/Qt/5.15.2/gcc_64/include/QtNetwork -I/home/vision/Qt/5.15.2/gcc_64/include/QtCore -I. -I/usr/include/libdrm -I/home/vision/Qt/5.15.2/gcc_64/mkspecs/linux-clang
QMAKE         = /home/vision/Qt/5.15.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/vision/Qt/5.15.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/vision/Qt/5.15.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ResizableSplitScreen1.0.0
DISTDIR = /home/vision/Desktop/qt/QT\ Projects/ResizableSplitScreen/build/Desktop_Qt_5_15_2_GCC_64bit-Debug/.tmp/ResizableSplitScreen1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/vision/Qt/5.15.2/gcc_64/lib -Wl,-rpath-link,/home/vision/Qt/5.15.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/vision/Qt/5.15.2/gcc_64/lib/libQt5QuickControls2.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5Quick.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5Multimedia.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5Gui.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5QmlModels.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5Qml.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5Network.so /home/vision/Qt/5.15.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../../main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = /home/vision/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/clang.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttracker.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttracker_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/linux-clang/qmake.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		../../../../ResizableSplitScreen.pro  ../../main.cpp
QMAKE_TARGET  = ResizableSplitScreen
DESTDIR       = 
TARGET        = ResizableSplitScreen


first: all
####### Build rules

ResizableSplitScreen:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../../ResizableSplitScreen.pro /home/vision/Qt/5.15.2/gcc_64/mkspecs/linux-clang/qmake.conf /home/vision/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/clang.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttracker.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttracker_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/linux-clang/qmake.conf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		../../ResizableSplitScreen.pro \
		../../qml.qrc
	$(QMAKE) -o Makefile ../../ResizableSplitScreen.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/common/clang.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttracker.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttracker_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttrackerqml.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/linux-clang/qmake.conf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf:
/home/vision/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf:
../../ResizableSplitScreen.pro:
../../qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile ../../ResizableSplitScreen.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ResizableSplitScreen

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/vision/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../../main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: ../../qml.qrc \
		/home/vision/Qt/5.15.2/gcc_64/bin/rcc \
		../../main.qml
	/home/vision/Qt/5.15.2/gcc_64/bin/rcc -name qml ../../qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/vision/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -Wall -Wextra -dM -E -o moc_predefs.h /home/vision/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: ../../main.cpp /home/vision/Qt/5.15.2/gcc_64/include/QtGui/QGuiApplication \
		/home/vision/Qt/5.15.2/gcc_64/include/QtGui/qguiapplication.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtGui/qinputmethod.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/QQmlApplicationEngine \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmlapplicationengine.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmlengine.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qjsengine.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qjsvalue.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qtqmlglobal.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qtqml-config.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmldebug.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqml.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmlprivate.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmlparserstatus.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmllist.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qpointer.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtCore/qmetaobject.h \
		/home/vision/Qt/5.15.2/gcc_64/include/QtQml/qqmlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../../main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ResizableSplitScreen/bin || mkdir -p $(INSTALL_ROOT)/opt/ResizableSplitScreen/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ResizableSplitScreen/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ResizableSplitScreen/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ResizableSplitScreen/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

